"""
Setup script for social_override MkDocs plugin

Install in editable mode with:
    pip install -e .
"""

from setuptools import setup, find_packages

setup(
    name='social_override',
    version='0.1.0',
    description='MkDocs plugin to override social media card images per page',
    author='Generated by install-mkdocs-template skill',
    packages=find_packages(),
    entry_points={
        'mkdocs.plugins': [
            'social_override = plugins.social_override:SocialOverridePlugin',
        ]
    },
    python_requires='>=3.8',
    install_requires=[
        'mkdocs>=1.0',
    ],
)
